### ISSUE TITLE
A chapter is missing from a novel

### ISSUE THREAD

**Issue by acertainpasserby** [LNReader/lnreader-sources#582]
### Source information

Novel Updates

### Steps to reproduce

1. Opened c76 part 2 of the novel 'I Was Admitted To The Villain School '
2. Showed error report with the reason 'no chapter'
3. Opened webview
4. Arrived at the novel webpage
5. Scrolled and open the chapter through the webpage 
6. Chapter exist 
7. Closed webview
8. Tried to read
9. Still show error
10. Report to github

### Expected behavior

c76 part 2 of the novel 'I Was Admitted To The Villain School' should have existed

### Actual behavior

Instead there was an error report page

### LNReader version

1.1.16

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.16](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
The URL of the chapter present in NovelUpdates is wrong, due to which the app can't read the chapter. You can directly use the SleepyTranslation source as a workaround.

URL for Chapter 76 Part 2 present in NovelUpdates: https://sleepytranslations.com/series/i-was-admitted-to-the-villain-school/chapter-762/

Actual URL: https://sleepytranslations.com/series/i-was-admitted-to-the-villain-school/chapter-76-2/
